### PR TITLE
Fixed addition bug

### PR DESCRIPTION
**Pull request by pwnfooj716**

### CODE REVIEW

**Comment by benwaffle** [comment]
silly boy

**Comment by halfbro** [comment]
ayy

**Comment by jgardella** [comment]
lmao

**Comment by benwaffle** [comment]
:alien:

**Comment by patgrasso** [comment]
ayyyyyy

**Comment by keevindoherty** [comment]
https://www.youtube.com/watch?v=vCadcBR95oU

**Comment by noisemaster** [comment]
https://www.youtube.com/watch?v=2QamU4-8NUw

**Pull request merged**
